### ISSUE TITLE
Backup handling for all the scenarios of configmap and secret usage

### ISSUE THREAD

**Issue by vineela1999** [soda-cdm/kahu#135]
**Issue/Feature Description:**
When a pod,deployment,daemonset or statefulset are associated with a configmap or a secret and backed up configmaps and secrets are not getting backed up along with backed up resource
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
configmaps and secrets should be backed up along with pod so that when restored ,pods come up
**How to reproduce, in case of a bug:**
```
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-val-config
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: SPECIAL_LEVEL
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: SPECIAL_TYPE
  restartPolicy: Never
```
```
apiVersion: v1
  kind: ConfigMap
  metadata:
    name: special-config
    namespace: default
  data:
    SPECIAL_LEVEL: very
    SPECIAL_TYPE: charm
```
bring up these yamls 
Then try to backup the pod above using the below yaml
```
apiVersion: kahu.io/v1beta1
kind: Backup
metadata:
  name: backup-demo-resource-pod-with-config
spec:
  includeNamespaces: [default]
  metadataLocation: nfs
  includeResources:
    - name: dapi-test-pod-val-config
      kind: Pod
      isRegex: false

```
Now see the backed up resources the configmap will not be backed up

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
